import type {
  ChoiceQuestion,
  ImageResponseQuestion,
  LongAnswerQuestion,
  OpenQuestion,
  PhotoAnswer,
  Question,
  ShortAnswerQuestion,
  UserAnswer,
} from "./types";

export const DEFAULT_SHORT_MAX_LENGTH = 300;
export const DEFAULT_LONG_MAX_LENGTH = 10_000;
/** The largest maxLength a quiz may set. */
export const MAX_TEXT_LENGTH = 50_000;
export const DEFAULT_MAX_IMAGES = 1;
/** The largest maxImages a quiz may set. */
export const MAX_IMAGES_LIMIT = 10;

export function isChoiceQuestion(question: Question): question is ChoiceQuestion {
  return question.type === "multiple_choice" || question.type === "multi_answer";
}

/** Questions the app cannot grade: written text and photo responses. */
export function isOpenQuestion(question: Question): question is OpenQuestion {
  return (
    question.type === "short_answer" ||
    question.type === "long_answer" ||
    question.type === "image_response"
  );
}

export function isTextQuestion(
  question: Question,
): question is ShortAnswerQuestion | LongAnswerQuestion {
  return question.type === "short_answer" || question.type === "long_answer";
}

export function isCodeQuestion(question: Question): question is LongAnswerQuestion {
  return question.type === "long_answer" && question.code === true;
}

export function textLimits(question: ShortAnswerQuestion | LongAnswerQuestion): {
  minLength: number;
  maxLength: number;
} {
  const fallback =
    question.type === "short_answer" ? DEFAULT_SHORT_MAX_LENGTH : DEFAULT_LONG_MAX_LENGTH;
  return { minLength: question.minLength ?? 0, maxLength: question.maxLength ?? fallback };
}

export function maxImagesOf(question: ImageResponseQuestion): number {
  return question.maxImages ?? DEFAULT_MAX_IMAGES;
}

export function isPhotoAnswer(value: UserAnswer | undefined): value is PhotoAnswer {
  return (
    !!value &&
    typeof value === "object" &&
    !Array.isArray(value) &&
    Array.isArray((value as PhotoAnswer).photos)
  );
}

// Photo file names are generated by the app, so they stay simple and safe.
const PHOTO_NAME = /^[A-Za-z0-9_-]{1,80}\.jpg$/;

export function isPhotoName(name: string): boolean {
  return PHOTO_NAME.test(name);
}

export function photosOf(value: UserAnswer | undefined): string[] {
  return isPhotoAnswer(value) ? value.photos : [];
}

/** The type-specific label shown in lists and badges. */
export function questionTypeLabel(question: Question): string {
  switch (question.type) {
    case "true_false":
      return "True / False";
    case "multiple_choice":
      return "Multiple choice";
    case "multi_answer":
      return "Select all";
    case "short_answer":
      return "Short answer";
    case "long_answer":
      return question.code ? "Code answer" : "Written answer";
    case "image_response":
      return "Photo answer";
  }
}
